# : Manager [[[

[mgr]
cwd = { fg = "{{colors.on_surface.default.hex}}" }

# Find
find_keyword = { fg = "{{colors.error.default.hex}}", bold = true, italic = true, underline = true }
find_position = { fg = "{{colors.error.default.hex}}", bold = true, italic = true }

# Marker
marker_copied = { fg = "{{colors.tertiary_container.default.hex}}", bg = "{{colors.tertiary_container.default.hex}}" }
marker_cut = { fg = "{{colors.tertiary_container.default.hex}}", bg = "{{colors.tertiary_container.default.hex}}" }
marker_marked = { fg = "{{colors.error.default.hex}}", bg = "{{colors.error.default.hex}}" }
marker_selected = { fg = "{{colors.tertiary.default.hex}}", bg = "{{colors.tertiary.default.hex}}" }

# Count
count_copied = { fg = "{{colors.on_tertiary_container.default.hex}}", bg = "{{colors.tertiary_container.default.hex}}" }
count_cut = { fg = "{{colors.on_tertiary_container.default.hex}}", bg = "{{colors.tertiary_container.default.hex}}" }
count_selected = { fg = "{{colors.on_primary.default.hex}}", bg = "{{colors.tertiary.default.hex}}" }

# Border
border_style  = { fg = "{{colors.primary.default.hex}}" }

# : ]]]


# : Status [[[

[status]
overall = { fg = "{{colors.primary.default.hex}}" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "{{colors.primary.default.hex}}", bg = "{{colors.surface.default.hex}}" }
progress_error = { fg = "{{colors.error.default.hex}}", bg = "{{colors.surface.default.hex}}" }

# Permissions
perm_type = { fg = "{{colors.secondary.default.hex}}" }
perm_write = { fg = "{{colors.tertiary.default.hex}}" }
perm_exec = { fg = "{{colors.error.default.hex}}" }
perm_read = { fg = "{{colors.tertiary_container.default.hex}}" }
perm_sep = { fg = "{{colors.primary_container.default.hex}}" }

# : ]]]


# : Mode [[[

[mode]

normal_main = { bg = "{{colors.primary.default.hex}}", fg = "{{colors.on_primary.default.hex}}", bold = true }
normal_alt  = { bg = "{{colors.surface_variant.default.hex}}", fg = "{{colors.on_surface_variant.default.hex}}" }

select_main = { bg = "{{colors.secondary.default.hex}}", fg = "{{colors.on_secondary.default.hex}}", bold = true }
select_alt  = { bg = "{{colors.surface_variant.default.hex}}", fg = "{{colors.on_surface_variant.default.hex}}" }

unset_main = { bg = "{{colors.tertiary.default.hex}}", fg = "{{colors.on_tertiary.default.hex}}", bold = true }
unset_alt  = { bg = "{{colors.surface_variant.default.hex}}", fg = "{{colors.on_surface_variant.default.hex}}" }

# : ]]]


# : Input [[[

[input]
border = { fg = "{{colors.primary.default.hex}}" }
title = {}
value = { fg = "{{colors.on_surface.default.hex}}" }
selected = { reversed = true }

# : ]]]


# : Tabs [[[

[tabs]
active = { fg = "{{colors.primary.default.hex}}", bold = true, bg = "{{colors.surface.default.hex}}" }
inactive = { fg = "{{colors.secondary.default.hex}}", bg = "{{colors.surface.default.hex}}" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "{{colors.primary.default.hex}}", bg = "{{colors.on_primary.default.hex}}" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "{{colors.primary.default.hex}}" }
title = {}
hovered = { fg = "{{colors.tertiary_container.default.hex}}", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "{{colors.surface.default.hex}}" }
cand = { fg = "{{colors.primary.default.hex}}" }
rest = { fg = "{{colors.on_primary.default.hex}}" }
desc = { fg = "{{colors.on_surface.default.hex}}" }
separator = " ▶ "
separator_style = { fg = "{{colors.on_surface.default.hex}}" }

# : ]]]

# : Spotter [[[

[spot]
border   = { fg = "{{colors.primary.default.hex}}" }
title    = { fg = "{{colors.primary.default.hex}}" }
tbl_col  = { fg = "{{colors.on_surface.default.hex}}" }
tbl_cell = { fg = "{{colors.on_surface.default.hex}}", bg = "{{colors.surface.default.hex}}" }

# : ]]]


# : Help [[[

[help]
on = { fg = "{{colors.on_surface.default.hex}}" }
run = { fg = "{{colors.on_surface.default.hex}}" }
hovered = { reversed = true, bold = true }
footer = { fg = "{{colors.on_secondary.default.hex}}", bg = "{{colors.secondary.default.hex}}" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "{{colors.tertiary.default.hex}}" }
title_warn = { fg = "{{colors.primary.default.hex}}" }
title_error = { fg = "{{colors.error.default.hex}}" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { mime = "*", is = "orphan", fg = "{{colors.on_error_container.default.hex}}", bg = "{{colors.error_container.default.hex}}" },
    { mime = "application/*exec*", fg = "{{colors.error.default.hex}}" },

    # Fallback
    { url = "*", fg = "{{colors.on_surface.default.hex}}" },
    { url = "*/", fg = "{{colors.primary.default.hex}}" },
]

# : ]]]
